export { default as Container } from './dumb/Container'
export { default as Link } from './dumb/Link'
export { default as Typography } from './dumb/Typography'
export { default as Switch } from './dumb/Switch'
export { default as Header } from './smart/Header'
export { default as Footer } from './smart/Footer'
