name: Deploy release to Netlify

on:
  push:
    tags:
      - 'v*'

jobs:
  deploy-prod:
    if: ${{ startsWith(github.ref, 'refs/tags/v') }}
    environment: prod
    runs-on: ubuntu-latest
    name: Deploy to Netlify
    env:
      working-directory: ${{ matrix.project }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v1

      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - if: steps.skip_check.outputs.should_skip != 'true'
        name: Install packages
        working-directory: ${{ env.working-directory }}
        run: yarn install

      - if: steps.skip_check.outputs.should_skip != 'true'
        name: Build project
        working-directory: ${{ env.working-directory }}
        run: yarn build

      - name: Deploy to netlify
        uses: netlify/actions/cli@master
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.DEV_NETLIFY_SITE_ID }}
        with:
          args: deploy --dir=build --prod
          secrets: '["NETLIFY_AUTH_TOKEN", "NETLIFY_SITE_ID"]'
