name: Deploy release to Netlify

on:
  push:
    tags:
      - v*

jobs:
  deploy-prod:
    if: ${{ startsWith(github.ref, 'refs/tags/v') }}
    environment: prod
    runs-on: ubuntu-latest
    name: Deploy to Netlify
    env:
      working-directory: ./
    steps:
      - name: Checkout code
        uses: actions/checkout@v1

      - name: Use Node.js 16.14.0
        uses: actions/setup-node@v1
        with:
          node-version: 16.14.0

      - if: steps.skip_check.outputs.should_skip != 'true'
        name: Install packages
        working-directory: ${{ env.working-directory }}
        run: yarn install

      - name: Test coverage
        run: yarn test:coverage

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          fail_ci_if_error: true
          verbose: true

      - if: steps.skip_check.outputs.should_skip != 'true'
        name: Create .env
        run: |
          touch .env
          echo REACT_APP_GITHUB_PERSONAL_ACCESS_TOKEN=${{ secrets.REACT_APP_GITHUB_PERSONAL_ACCESS_TOKEN }} >> .env
          echo REACT_APP_ANALYTICS_TOKEN=${{ secrets.REACT_APP_ANALYTICS_TOKEN }} >> .env
          cat .env

      - if: steps.skip_check.outputs.should_skip != 'true'
        name: Build project
        working-directory: ${{ env.working-directory }}
        run: yarn build

      - if: steps.skip_check.outputs.should_skip != 'true'
        name: Deploy to netlify
        uses: netlify/actions/cli@master
        with:
          args: deploy --auth ${{ secrets.NETLIFY_AUTH_TOKEN }} --dir=build --prod
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
