name: Deploy release to Netlify

on:
  push:
    tags:
      - v*

jobs:
  deploy-prod:
    if: ${{ startsWith(github.ref, 'refs/tags/v') }}
    environment: prod
    runs-on: ubuntu-latest
    name: Deploy to Netlify
    env:
      working-directory: ./
    steps:
      - name: Checkout code
        uses: actions/checkout@v1

      - name: Use Node.js 16.14.0
        uses: actions/setup-node@v1
        with:
          node-version: 16.14.0

      - if: steps.skip_check.outputs.should_skip != 'true'
        name: Install packages
        working-directory: ${{ env.working-directory }}
        run: yarn install

      - if: steps.skip_check.outputs.should_skip != 'true'
        name: Test coverage
        uses: ArtiomTr/jest-coverage-report-action@v2
        with:
          package-manager: yarn
          test-script: yarn test:coverage

      - if: steps.skip_check.outputs.should_skip != 'true'
        name: Build project
        working-directory: ${{ env.working-directory }}
        run: yarn build

      - name: Deploy to netlify
        uses: netlify/actions/cli@master
        with:
          args: deploy --auth ${{ secrets.NETLIFY_AUTH_TOKEN }} --dir=build --prod
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
